version: '3.3'

services:
    db:
        image: mysql:8.0.19
        container_name: cloud-run-backend-example-db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports: ['3306:3306']
        environment:
            MYSQL_DATABASE: cloud-run-backend-example
            MYSQL_USER: cloud-run-backend-example
            MYSQL_PASSWORD: cloud-run-backend-example
            MYSQL_ROOT_PASSWORD: cloud-run-backend-example
    minio:
        image: minio/minio
        environment:
          - MINIO_ROOT_USER=cloud-run-backend-example
          - MINIO_ROOT_PASSWORD=cloud-run-backend-example
        restart: always
        command: server /data --console-address ":9001"
        ports:
          - 9000:9000
          - 9001:9001
    minio-client:
        image: minio/mc
        environment:
          - MINIO_ACCESS_KEY=cloud-run-backend-example
          - MINIO_SECRET_KEY=cloud-run-backend-example
          - MINIO_BUCKET=cloud-run-backend-example.bucket
          - MINIO_HOST=minio
          - MINIO_PORT=9000
          - MINIO_IMAGES_DIR=images/
        volumes: ["./minio.init:/minio.init"]
        entrypoint: sh
        depends_on: ["minio"]
        command: /minio.init/init.sh
